print('welcome to swastik learning')
print("enter the character input:")
x = input("word: ")
print(x)
print("enter integer no:")
a = int(input("integer: "))
print("enter the floating no:")
b = float(input("float: "))
print(b)